stages:
  dvc_optuna:
    cmd: python stages/dvc_optuna.py
    deps:
      - requirements.txt
      - stages/dvc_optuna.py

    outs:
      - ${paths.trial_model}:
          checkpoint: true
      - ${paths.study}
    params:
      - seed
      - n_trials
    metrics:
      - ${paths.metrics}
