stages:
  dvc_optuna:
    cmd: python stages/dvc_optuna.py
    deps:
      - requirements.txt
      - stages/dvc_optuna.py

    outs:
      - ${paths.study}
    params:
      - seed
      - n_trials
    # metrics:
    #   - ${paths.metrics}
    plots:
      - dvlive-optuna/plots/metrics/metric.tsv
